version: '3.3'
services:
    fileserver:
        container_name: 'fileerver'
        build: './fileserver'
        ports: 
            - '8080:8080'
        volumes:
            - './fileserver:/go/src/fileserver'
        depends_on:
            - 'mongo'
    api:
        container_name: 'api'
        build: './api'
        ports:
            - '3000:3000'
        volumes:
            - './api:/go/src/app'
        depends_on: 
            - 'mongo'
            - 'redis'
    mongo:
        image: 'mongo:latest'
        container_name: 'mongo'
        ports: 
            - '27100:27017'


    redis:
        image: 'redis:latest'
        environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
            - '6379:6379'
